-- Lists
--
-- Lists also allow us to contain multiple values within a single value.
-- However they vary from tuples in the following ways:
--  1) all elements of a list must be of the same type
--  2) Lists have a '[]' syntax compared to the '(,)' syntax of tuples
--  3) The number of values that will be in the list does not have to be
--  predetermined, and can change. 
--
--  The various list functions that we've covered in a previous chapter
--  still hold here. (Refer to chapter 3) 

